### ISSUE TITLE
Problems creating stacks

### ISSUE THREAD

**Issue by IvRRimum** [commonsearch/cosr-ops#19] opened 2016-05-23 14:48 UTC
When i run `make aws_elasticsearch_create` i get the following error:
`The following resource(s) failed to create: [ElasticsearchLbLaunchConfiguration, ElasticsearchMasterLaunchConfiguration, ElasticsearchDataLaunchConfiguration]. . Rollback requested by user.`

Been hung up on this for past few hours.

**Comment by sylvinus** [comment] 2016-05-25 21:30
Duplicate of #20

**Closed as completed by sylvinus** 2016-05-25 21:30 UTC
